version: "3.9"

services:
  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - flask_app