services:
  flask:
    build:
      context: flask
    restart: always
    expose:
      - 5000

  nginx:
    build: nginx
    restart: always
    volumes:
      - ./nginx/confi/:/etc/nginx/conf.d/:ro
      - ./nginx/self.crt:/etc/ssl/certs/self.crt:ro
      - ./nginx/self.key:/etc/ssl/private/self.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - flask
